### ISSUE TITLE
Last layer of network

### ISSUE THREAD

**Issue by tianfanzhu** [chenzhi1992/TensorRT-SSD#1]
hello. i saw that u used createSSDDetectionOutputLayer in pluginimplement.cpp to declare the last layer of SSD, but in the deploy prototxt you commented out that layer. Can you explain why? Are you able to release an sample of how to run this code?

**Comment by chenzhi1992** [comment]
@tianfanzhu, hi, I wrote the createSSDDetectionOutputLayer function in pluginimplement.cpp , but I didn't use it. Because there's going to be a mistake，if you use this function.  I reimplemented this function by using the outputs of mbox_loc, mbox_prior, mbox_conf layer . I'll publish the code later. Please pay attention to my github.

**Comment by tianfanzhu** [comment]
Thank you, I will look forward to it. Are you, by the way, able to approximate when this is fully released?

**Comment by hectorgui** [comment]
> @tianfanzhu, hi, I wrote the createSSDDetectionOutputLayer function in pluginimplement.cpp , but I didn't use it. Because there's going to be a mistake，if you use this function. I reimplemented this function by using the outputs of mbox_loc, mbox_prior, mbox_conf layer . I'll publish the code later. Please pay attention to my github.

Hi chenzhi, have you ever upload your new code?
